id: P006731
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25101
  title: དབུ་མ་འཇུག་པའི་རང་འགྲེལ།
  author: ''
  volumes:
    a7f5618c275f41ca9d7bab28c7ff001e:
      image_group_id: I1KG25103
      title: ''
      volume_number: 1
      total_pages: 480
      base_file: v001.txt
