id: I801440DF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:34:35+00:00'
last_modified: '2022-06-08T06:27:40.470103+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25101
  title: དབུ་མ་འཇུག་པའི་རང་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    42F0:
      image_group_id: I1KG25103
      title: ''
      total_pages: 480
      order: 1
      base_file: 42F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
